### ISSUE TITLE
can you share pdf

### ISSUE THREAD

**Issue by Sandy4321** [passalis/boew#1]
can you add pdf to repo?

**Comment by Sandy4321** [comment]
link is broken 
http://poseidon.csd.auth.gr/papers/PUBLISHED/JOURNAL/pdf/2018/Passalis_PatternRecognition_2018.pdf

**Comment by passalis** [comment]
Thanks for letting me know. I added a (working) link to the pdf to the repo. You can find the paper [here](https://passalis.github.io/assets/pdf/papers/j2.pdf).

**Comment by Sandy4321** [comment]
great thanks
by the way, what would be simple python code to learn BoF for time series
I attended this meetup
https://www.meetup.com/Deep-Learning-Toronto-Meetup/events/261041423/
but some simple code/explanations  needed to learn basics

**Comment by passalis** [comment]
I wasn't aware of this meetup. Happy to hear about this!!! I will soon share the code (PyTorch) implementing the method and allowing for reproducing the results reported in the paper. I will let you know.

**Comment by Sandy4321** [comment]
great thanks, meantime, may you help find some very simple explanation with code how BoF works with time series to learn from very beginning main ideas of BOF for time series?
